-- =============================================================================
-- Migration 0015: H6 question steps
-- =============================================================================
-- Inserts 198 question steps for H6 into question_steps_new.
-- Questions in questions_new are matched by topic_slug + cluster_slug + order_index.
-- =============================================================================

BEGIN;

INSERT INTO public.question_steps_new (question_id, step_order, step_description)
SELECT q.id, s.step_order, s.description
FROM (VALUES
  ('h6_machten', 'negatieve_macht', 1, 1, 'Schrijf de breuk als negatieve macht: $\dfrac{6}{x} = 6x^{-1}$.'),
  ('h6_machten', 'negatieve_macht', 1, 2, 'Pas de machtsregel toe: $f''(x) = -1 \cdot 6x^{-2} = -6x^{-2}$.'),
  ('h6_machten', 'negatieve_macht', 1, 3, 'Schrijf terug als breuk (afspraak: geen negatieve exponenten): $f''(x) = -\dfrac{6}{x^2}$.'),
  ('h6_machten', 'negatieve_macht', 2, 1, 'Schrijf om: $\dfrac{1}{x^2} = x^{-2}$.'),
  ('h6_machten', 'negatieve_macht', 2, 2, 'Pas de machtsregel toe: $f''(x) = -2x^{-3}$.'),
  ('h6_machten', 'negatieve_macht', 2, 3, 'Schrijf terug: $f''(x) = -\dfrac{2}{x^3}$.'),
  ('h6_machten', 'negatieve_macht', 3, 1, 'Schrijf om: $\dfrac{6}{x^3} = 6x^{-3}$.'),
  ('h6_machten', 'negatieve_macht', 3, 2, 'Pas de machtsregel toe: $f''(x) = -3 \cdot 6x^{-4} = -18x^{-4}$.'),
  ('h6_machten', 'negatieve_macht', 3, 3, 'Schrijf terug: $f''(x) = -\dfrac{18}{x^4}$.'),
  ('h6_machten', 'negatieve_macht', 4, 1, 'Differentieer termsgewijs. De $5$ heeft afgeleide $0$.'),
  ('h6_machten', 'negatieve_macht', 4, 2, 'Voor $-\dfrac{3}{x^2} = -3x^{-2}$: afgeleide is $-3 \cdot (-2)x^{-3} = 6x^{-3}$.'),
  ('h6_machten', 'negatieve_macht', 4, 3, 'Schrijf terug: $g''(x) = \dfrac{6}{x^3}$.'),
  ('h6_machten', 'negatieve_macht', 5, 1, 'Differentieer termsgewijs met de machtsregel. Behandel $a$ en $b$ als constanten.'),
  ('h6_machten', 'negatieve_macht', 5, 2, '$[ax^4]'' = 4ax^3$ en $\left[-\dfrac{b}{x^4}\right]'' = [-bx^{-4}]'' = 4bx^{-5}$.'),
  ('h6_machten', 'negatieve_macht', 5, 3, 'Schrijf terug: $h''(x) = 4ax^3 + \dfrac{4b}{x^5}$.'),
  ('h6_machten', 'negatieve_macht', 6, 1, 'Differentieer termsgewijs.'),
  ('h6_machten', 'negatieve_macht', 6, 2, '$[5x^2]'' = 10x$ en $\left[-\dfrac{5}{x^2}\right]'' = [-5x^{-2}]'' = 10x^{-3}$.'),
  ('h6_machten', 'negatieve_macht', 6, 3, 'Schrijf terug: $f''(x) = 10x + \dfrac{10}{x^3}$.'),
  ('h6_machten', 'uitdelen', 1, 1, 'Deel de teller door de noemer: $\dfrac{2x-1}{x^3} = \dfrac{2x}{x^3} - \dfrac{1}{x^3} = 2x^{-2} - x^{-3}$.'),
  ('h6_machten', 'uitdelen', 1, 2, 'Pas de machtsregel toe: $f''(x) = -4x^{-3} + 3x^{-4}$.'),
  ('h6_machten', 'uitdelen', 1, 3, 'Schrijf terug: $f''(x) = -\dfrac{4}{x^3} + \dfrac{3}{x^4}$.'),
  ('h6_machten', 'uitdelen', 2, 1, 'Deel de teller door de noemer: $\dfrac{x^3+1}{x^3} = 1 + x^{-3}$.'),
  ('h6_machten', 'uitdelen', 2, 2, 'Differentieer: $[1]'' = 0$ en $[x^{-3}]'' = -3x^{-4}$.'),
  ('h6_machten', 'uitdelen', 2, 3, 'Schrijf terug: $f''(x) = -\dfrac{3}{x^4}$.'),
  ('h6_machten', 'uitdelen', 3, 1, 'Deel de teller door de noemer: $\dfrac{x^2+1}{x} = x + x^{-1}$.'),
  ('h6_machten', 'uitdelen', 3, 2, 'Differentieer: $[x]'' = 1$ en $[x^{-1}]'' = -x^{-2}$.'),
  ('h6_machten', 'uitdelen', 3, 3, 'Schrijf terug: $g''(x) = 1 - \dfrac{1}{x^2}$.'),
  ('h6_machten', 'uitdelen', 4, 1, 'Deel de teller door de noemer: $\dfrac{3x^6-3}{x^3} = 3x^3 - 3x^{-3}$.'),
  ('h6_machten', 'uitdelen', 4, 2, 'Differentieer: $[3x^3]'' = 9x^2$ en $[-3x^{-3}]'' = 9x^{-4}$.'),
  ('h6_machten', 'uitdelen', 4, 3, 'Schrijf terug: $h''(x) = 9x^2 + \dfrac{9}{x^4}$.'),
  ('h6_machten', 'uitdelen', 5, 1, 'Controleer of uitdelen mogelijk is: teller $x^2-1$ en noemer $6-x^2$ hebben geen gemeenschappelijke factor.'),
  ('h6_machten', 'uitdelen', 5, 2, 'Uitdelen lukt hier niet — de quotiëntregel is nodig (zie $h2\_quotientregel$).'),
  ('h6_machten', 'uitdelen', 5, 3, 'Dit is een herkenvraag: niet elke breuk kan uitgedeeld worden.'),
  ('h6_machten', 'uitdelen', 6, 1, 'Deel de teller door de noemer: $\dfrac{2x^2-5}{2x^2} = 1 - \dfrac{5}{2x^2} = 1 - \tfrac{5}{2}x^{-2}$.'),
  ('h6_machten', 'uitdelen', 6, 2, 'Differentieer: $[1]'' = 0$ en $\left[-\tfrac{5}{2}x^{-2}\right]'' = 5x^{-3}$.'),
  ('h6_machten', 'uitdelen', 6, 3, 'Schrijf terug: $f''(x) = \dfrac{5}{x^3}$.'),
  ('h6_machten', 'wortelvorm', 1, 1, 'Schrijf de wortel als machtsvorm: $\sqrt{x} = x^{\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 1, 2, 'Pas de machtsregel toe: $f''(x) = \tfrac{1}{2}x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 1, 3, 'Schrijf terug zonder gebroken exponent: $f''(x) = \dfrac{1}{2\sqrt{x}}$.'),
  ('h6_machten', 'wortelvorm', 2, 1, 'Schrijf om: $2\sqrt{x} = 2x^{\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 2, 2, 'Pas de machtsregel toe: $f''(x) = 2 \cdot \tfrac{1}{2}x^{-\frac{1}{2}} = x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 2, 3, 'Schrijf terug: $f''(x) = \dfrac{1}{\sqrt{x}}$.'),
  ('h6_machten', 'wortelvorm', 3, 1, 'Schrijf beide termen als machten: $\sqrt{x} = x^{\frac{1}{2}}$ en $\dfrac{1}{\sqrt{x}} = x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 3, 2, 'Differentieer termsgewijs: $[\sqrt{x}]'' = \tfrac{1}{2}x^{-\frac{1}{2}}$ en $[-x^{-\frac{1}{2}}]'' = \tfrac{1}{2}x^{-\frac{3}{2}}$.'),
  ('h6_machten', 'wortelvorm', 3, 3, 'Schrijf terug: $g''(x) = \dfrac{1}{2\sqrt{x}} + \dfrac{1}{2x\sqrt{x}}$.'),
  ('h6_machten', 'wortelvorm', 4, 1, 'Schrijf om: $3\sqrt{x} = 3x^{\frac{1}{2}}$. De $5$ heeft afgeleide $0$.'),
  ('h6_machten', 'wortelvorm', 4, 2, 'Differentieer: $[3x^{\frac{1}{2}}]'' = \tfrac{3}{2}x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 4, 3, 'Schrijf terug: $f''(x) = \dfrac{3}{2\sqrt{x}}$.'),
  ('h6_machten', 'wortelvorm', 5, 1, 'Schrijf om: $\dfrac{1}{\sqrt{x}} = x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'wortelvorm', 5, 2, 'Pas de machtsregel toe: $h''(x) = -\tfrac{1}{2}x^{-\frac{3}{2}}$.'),
  ('h6_machten', 'wortelvorm', 5, 3, 'Schrijf terug: $h''(x) = -\dfrac{1}{2x\sqrt{x}}$.'),
  ('h6_machten', 'wortelvorm', 6, 1, 'Schrijf het product als één macht: $x^3 \cdot \sqrt{x} = x^3 \cdot x^{\frac{1}{2}} = x^{\frac{7}{2}}$.'),
  ('h6_machten', 'wortelvorm', 6, 2, 'Pas de machtsregel toe: $k''(x) = \tfrac{7}{2}x^{\frac{5}{2}}$.'),
  ('h6_machten', 'wortelvorm', 6, 3, 'Schrijf terug: $k''(x) = 3{,}5x^2\sqrt{x}$ (want $x^{\frac{5}{2}} = x^2\sqrt{x}$).'),
  ('h6_machten', 'gemengd_macht_wortel', 1, 1, 'Schrijf het product als één macht: $x \cdot \sqrt{x} = x^1 \cdot x^{\frac{1}{2}} = x^{\frac{3}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 1, 2, 'Pas de machtsregel toe: $f''(x) = \tfrac{3}{2}x^{\frac{1}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 1, 3, 'Schrijf terug: $f''(x) = 1{,}5\sqrt{x}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 2, 1, 'Schrijf het product als één macht: $x^2 \cdot \sqrt{x} = x^{\frac{5}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 2, 2, 'Pas de machtsregel toe: $f''(x) = \tfrac{5}{2}x^{\frac{3}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 2, 3, 'Schrijf terug: $f''(x) = 2{,}5x\sqrt{x}$ (want $x^{\frac{3}{2}} = x\sqrt{x}$).'),
  ('h6_machten', 'gemengd_macht_wortel', 3, 1, 'Schrijf het quotiënt als één macht: $\dfrac{x}{\sqrt{x}} = x^1 \cdot x^{-\frac{1}{2}} = x^{\frac{1}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 3, 2, 'Pas de machtsregel toe: $g''(x) = \tfrac{1}{2}x^{-\frac{1}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 3, 3, 'Schrijf terug: $g''(x) = \dfrac{1}{2\sqrt{x}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 4, 1, 'Schrijf om: $\dfrac{1}{x\sqrt{x}} = x^{-1} \cdot x^{-\frac{1}{2}} = x^{-\frac{3}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 4, 2, 'Pas de machtsregel toe: $h''(x) = -\tfrac{3}{2}x^{-\frac{5}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 4, 3, 'Schrijf terug: $h''(x) = -\dfrac{1{,}5}{x^2\sqrt{x}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 5, 1, 'Schrijf het product uit: $x^2(x\sqrt{x} - 3) = x^2 \cdot x^{\frac{3}{2}} - 3x^2 = x^{\frac{7}{2}} - 3x^2$.'),
  ('h6_machten', 'gemengd_macht_wortel', 5, 2, 'Differentieer termsgewijs: $[x^{\frac{7}{2}}]'' = \tfrac{7}{2}x^{\frac{5}{2}}$ en $[-3x^2]'' = -6x$.'),
  ('h6_machten', 'gemengd_macht_wortel', 5, 3, 'Schrijf terug: $k''(x) = 3{,}5x^2\sqrt{x} - 6x$ (want $x^{\frac{5}{2}} = x^2\sqrt{x}$).'),
  ('h6_machten', 'gemengd_macht_wortel', 6, 1, 'Schrijf het quotiënt uit via deling: $\dfrac{x^2-2}{x\sqrt{x}} = \dfrac{x^2}{x^{\frac{3}{2}}} - \dfrac{2}{x^{\frac{3}{2}}} = x^{\frac{1}{2}} - 2x^{-\frac{3}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 6, 2, 'Differentieer termsgewijs: $[x^{\frac{1}{2}}]'' = \tfrac{1}{2}x^{-\frac{1}{2}}$ en $[-2x^{-\frac{3}{2}}]'' = 3x^{-\frac{5}{2}}$.'),
  ('h6_machten', 'gemengd_macht_wortel', 6, 3, 'Schrijf terug: $f''(x) = \dfrac{0{,}5}{\sqrt{x}} + \dfrac{3}{x^2\sqrt{x}}$.'),
  ('h6_kettingregel', 'macht_lineair', 1, 1, 'Herken de samengestelde functie: $f(x) = u(v(x))$ met $u(v) = v^3$ en $v(x) = 4x + 3$.'),
  ('h6_kettingregel', 'macht_lineair', 1, 2, 'Bepaal de afgeleiden: $u''(v) = 3v^2$ en $v''(x) = 4$.'),
  ('h6_kettingregel', 'macht_lineair', 1, 3, 'Pas de kettingregel toe: $f''(x) = u''(v(x)) \cdot v''(x) = 3(4x+3)^2 \cdot 4 = 12(4x+3)^2$.'),
  ('h6_kettingregel', 'macht_lineair', 2, 1, 'Herken de samengestelde functie: $u(v) = v^4$ en $v(x) = 2x - 1$.'),
  ('h6_kettingregel', 'macht_lineair', 2, 2, 'Bepaal de afgeleiden: $u''(v) = 4v^3$ en $v''(x) = 2$.'),
  ('h6_kettingregel', 'macht_lineair', 2, 3, 'Pas de kettingregel toe: $f''(x) = 4(2x-1)^3 \cdot 2 = 8(2x-1)^3$.'),
  ('h6_kettingregel', 'macht_lineair', 3, 1, 'Herken: $u(v) = 6v^5$ en $v(x) = \tfrac{1}{2}x - 4$. Let op de constante factor $6$.'),
  ('h6_kettingregel', 'macht_lineair', 3, 2, 'Bepaal de afgeleiden: $u''(v) = 30v^4$ en $v''(x) = \tfrac{1}{2}$.'),
  ('h6_kettingregel', 'macht_lineair', 3, 3, 'Pas de kettingregel toe: $g''(x) = 30(\tfrac{1}{2}x-4)^4 \cdot \tfrac{1}{2} = 15(\tfrac{1}{2}x - 4)^4$.'),
  ('h6_kettingregel', 'macht_lineair', 4, 1, 'Herken: $u(v) = -2v^4$ en $v(x) = 2x + 1$.'),
  ('h6_kettingregel', 'macht_lineair', 4, 2, 'Bepaal de afgeleiden: $u''(v) = -8v^3$ en $v''(x) = 2$.'),
  ('h6_kettingregel', 'macht_lineair', 4, 3, 'Pas de kettingregel toe: $h''(x) = -8(2x+1)^3 \cdot 2 = -16(2x+1)^3$.'),
  ('h6_kettingregel', 'macht_lineair', 5, 1, 'Splits met de somregel: $[5x]'' = 5$ en $\left[-\dfrac{4}{(3x+2)^3}\right]'' = [-4(3x+2)^{-3}]''$.'),
  ('h6_kettingregel', 'macht_lineair', 5, 2, 'Pas de kettingregel toe op het tweede deel: $u''(v) = 12v^{-4}$ en $v''(x) = 3$, geeft $-4 \cdot (-3)(3x+2)^{-4} \cdot 3 = 36(3x+2)^{-4}$.'),
  ('h6_kettingregel', 'macht_lineair', 5, 3, 'Combineer en schrijf terug: $f''(x) = 5 + \dfrac{36}{(3x+2)^4}$.'),
  ('h6_kettingregel', 'macht_lineair', 6, 1, 'Splits met de somregel: $[3x^2]'' = 6x$ en $\left[-\tfrac{1}{2}(x-2)^3\right]''$.'),
  ('h6_kettingregel', 'macht_lineair', 6, 2, 'Pas de kettingregel toe op het tweede deel: $u''(v) = -\tfrac{3}{2}v^2$ en $v''(x) = 1$, geeft $-\tfrac{3}{2}(x-2)^2$.'),
  ('h6_kettingregel', 'macht_lineair', 6, 3, 'Combineer: $k''(x) = 6x - 1{,}5(x-2)^2$.'),
  ('h6_kettingregel', 'macht_polynoom', 1, 1, 'Herken de samengestelde functie: $u(v) = v^3$ en $v(x) = x^2 + 1$.'),
  ('h6_kettingregel', 'macht_polynoom', 1, 2, 'Bepaal de afgeleiden: $u''(v) = 3v^2$ en $v''(x) = 2x$.'),
  ('h6_kettingregel', 'macht_polynoom', 1, 3, 'Pas de kettingregel toe: $f''(x) = 3(x^2+1)^2 \cdot 2x = 6x(x^2+1)^2$.'),
  ('h6_kettingregel', 'macht_polynoom', 2, 1, 'Herken: $u(v) = v^4$ en $v(x) = 4x^2 - 3$.'),
  ('h6_kettingregel', 'macht_polynoom', 2, 2, 'Bepaal de afgeleiden: $u''(v) = 4v^3$ en $v''(x) = 8x$.'),
  ('h6_kettingregel', 'macht_polynoom', 2, 3, 'Pas de kettingregel toe: $f''(x) = 4(4x^2-3)^3 \cdot 8x = 32x(4x^2-3)^3$.'),
  ('h6_kettingregel', 'macht_polynoom', 3, 1, 'Herken: $u(v) = 4v^2$ en $v(x) = x^3 + 7x - 2$.'),
  ('h6_kettingregel', 'macht_polynoom', 3, 2, 'Bepaal de afgeleiden: $u''(v) = 8v$ en $v''(x) = 3x^2 + 7$.'),
  ('h6_kettingregel', 'macht_polynoom', 3, 3, 'Pas de kettingregel toe: $g''(x) = 8(x^3+7x-2) \cdot (3x^2+7) = 8(3x^2+7)(x^3+7x-2)$.'),
  ('h6_kettingregel', 'macht_polynoom', 4, 1, 'Herken: $u(v) = v^3$ en $v(x) = x^2 - 2x + 3$.'),
  ('h6_kettingregel', 'macht_polynoom', 4, 2, 'Bepaal de afgeleiden: $u''(v) = 3v^2$ en $v''(x) = 2x - 2$.'),
  ('h6_kettingregel', 'macht_polynoom', 4, 3, 'Pas de kettingregel toe: $h''(x) = 3(x^2-2x+3)^2 \cdot (2x-2) = 3(2x-2)(x^2-2x+3)^2$.'),
  ('h6_kettingregel', 'macht_polynoom', 5, 1, 'Herken: $u(v) = v^3$ en $v(x) = x^2 - 5$.'),
  ('h6_kettingregel', 'macht_polynoom', 5, 2, 'Bepaal de afgeleiden: $u''(v) = 3v^2$ en $v''(x) = 2x$.'),
  ('h6_kettingregel', 'macht_polynoom', 5, 3, 'Pas de kettingregel toe: $f''(x) = 3(x^2-5)^2 \cdot 2x = 6x(x^2-5)^2$.'),
  ('h6_kettingregel', 'macht_polynoom', 6, 1, 'Herken: $u(v) = v^3$ en $v(x) = \tfrac{1}{2}x^2 - 2x$.'),
  ('h6_kettingregel', 'macht_polynoom', 6, 2, 'Bepaal de afgeleiden: $u''(v) = 3v^2$ en $v''(x) = x - 2$.'),
  ('h6_kettingregel', 'macht_polynoom', 6, 3, 'Pas de kettingregel toe: $k''(x) = 3(\tfrac{1}{2}x^2-2x)^2 \cdot (x-2) = 3(x-2)(\tfrac{1}{2}x^2-2x)^2$.'),
  ('h6_kettingregel', 'wortel_lineair', 1, 1, 'Schrijf de wortel als macht: $\sqrt{4x+1} = (4x+1)^{\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 1, 2, 'Pas de kettingregel toe: $u''(v) = \tfrac{1}{2}v^{-\frac{1}{2}}$ en $v''(x) = 4$, geeft $f''(x) = \tfrac{1}{2}(4x+1)^{-\frac{1}{2}} \cdot 4 = 2(4x+1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 1, 3, 'Schrijf terug: $f''(x) = \dfrac{2}{\sqrt{4x+1}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 2, 1, 'Schrijf om: $\sqrt{3x+1} = (3x+1)^{\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 2, 2, 'Pas de kettingregel toe: $f''(x) = \tfrac{1}{2}(3x+1)^{-\frac{1}{2}} \cdot 3 = \tfrac{3}{2}(3x+1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 2, 3, 'Schrijf terug: $f''(x) = \dfrac{3}{2\sqrt{3x+1}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 3, 1, 'Schrijf om: $\sqrt{2x-5} = (2x-5)^{\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 3, 2, 'Pas de kettingregel toe: $g''(x) = \tfrac{1}{2}(2x-5)^{-\frac{1}{2}} \cdot 2 = (2x-5)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 3, 3, 'Schrijf terug: $g''(x) = \dfrac{1}{\sqrt{2x-5}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 4, 1, 'Schrijf om: $3\sqrt{2x+1} = 3(2x+1)^{\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 4, 2, 'Pas de kettingregel toe: $h''(x) = 3 \cdot \tfrac{1}{2}(2x+1)^{-\frac{1}{2}} \cdot 2 = 3(2x+1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 4, 3, 'Schrijf terug: $h''(x) = \dfrac{3}{\sqrt{2x+1}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 5, 1, 'Schrijf om: $\dfrac{1}{\sqrt{4x-1}} = (4x-1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 5, 2, 'Pas de kettingregel toe: $f''(x) = -\tfrac{1}{2}(4x-1)^{-\frac{3}{2}} \cdot 4 = -2(4x-1)^{-\frac{3}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 5, 3, 'Schrijf terug: $f''(x) = -\dfrac{2}{(4x-1)\sqrt{4x-1}}$ (want $(4x-1)^{\frac{3}{2}} = (4x-1)\sqrt{4x-1}$).'),
  ('h6_kettingregel', 'wortel_lineair', 6, 1, 'Schrijf om: $5\sqrt{3x-2} = 5(3x-2)^{\frac{1}{2}}$. De $7$ heeft afgeleide $0$.'),
  ('h6_kettingregel', 'wortel_lineair', 6, 2, 'Pas de kettingregel toe: $f''(x) = 5 \cdot \tfrac{1}{2}(3x-2)^{-\frac{1}{2}} \cdot 3 = \tfrac{15}{2}(3x-2)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_lineair', 6, 3, 'Schrijf terug: $k''(x) = \dfrac{7{,}5}{\sqrt{3x-2}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 1, 1, 'Schrijf om: $\sqrt{x^2+1} = (x^2+1)^{\frac{1}{2}}$. Herken $v(x) = x^2 + 1$.'),
  ('h6_kettingregel', 'wortel_polynoom', 1, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $f''(x) = \tfrac{1}{2}(x^2+1)^{-\frac{1}{2}} \cdot 2x = x(x^2+1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 1, 3, 'Schrijf terug: $f''(x) = \dfrac{x}{\sqrt{x^2+1}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 2, 1, 'Schrijf om: $\sqrt{x^2+9} = (x^2+9)^{\frac{1}{2}}$. Herken $v(x) = x^2 + 9$.'),
  ('h6_kettingregel', 'wortel_polynoom', 2, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $f''(x) = \tfrac{1}{2}(x^2+9)^{-\frac{1}{2}} \cdot 2x$.'),
  ('h6_kettingregel', 'wortel_polynoom', 2, 3, 'Schrijf terug: $f''(x) = \dfrac{x}{\sqrt{x^2+9}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 3, 1, 'Schrijf om: $\sqrt{2x^2+4x} = (2x^2+4x)^{\frac{1}{2}}$. Herken $v(x) = 2x^2 + 4x$.'),
  ('h6_kettingregel', 'wortel_polynoom', 3, 2, 'Bepaal $v''(x) = 4x + 4$. Pas de kettingregel toe: $g''(x) = \tfrac{1}{2}(2x^2+4x)^{-\frac{1}{2}} \cdot (4x+4)$.'),
  ('h6_kettingregel', 'wortel_polynoom', 3, 3, 'Schrijf terug: $g''(x) = \dfrac{2x+2}{\sqrt{2x^2+4x}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 4, 1, 'Schrijf om: $\sqrt{x^3+3x} = (x^3+3x)^{\frac{1}{2}}$. Herken $v(x) = x^3 + 3x$.'),
  ('h6_kettingregel', 'wortel_polynoom', 4, 2, 'Bepaal $v''(x) = 3x^2 + 3$. Pas de kettingregel toe: $h''(x) = \tfrac{1}{2}(x^3+3x)^{-\frac{1}{2}} \cdot (3x^2+3)$.'),
  ('h6_kettingregel', 'wortel_polynoom', 4, 3, 'Schrijf terug: $h''(x) = \dfrac{3x^2+3}{2\sqrt{x^3+3x}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 5, 1, 'Schrijf om: $\sqrt{x^2+2x+3} = (x^2+2x+3)^{\frac{1}{2}}$. Herken $v(x) = x^2+2x+3$.'),
  ('h6_kettingregel', 'wortel_polynoom', 5, 2, 'Bepaal $v''(x) = 2x + 2$. Pas de kettingregel toe: $f''(x) = \tfrac{1}{2}(x^2+2x+3)^{-\frac{1}{2}} \cdot (2x+2)$.'),
  ('h6_kettingregel', 'wortel_polynoom', 5, 3, 'Schrijf terug: $f''(x) = \dfrac{x+1}{\sqrt{x^2+2x+3}}$.'),
  ('h6_kettingregel', 'wortel_polynoom', 6, 1, 'Schrijf om: $5\sqrt{2x^4+x^2} = 5(2x^4+x^2)^{\frac{1}{2}}$. Herken $v(x) = 2x^4+x^2$.'),
  ('h6_kettingregel', 'wortel_polynoom', 6, 2, 'Bepaal $v''(x) = 8x^3 + 2x$. Pas de kettingregel toe: $k''(x) = 5 \cdot \tfrac{1}{2}(2x^4+x^2)^{-\frac{1}{2}} \cdot (8x^3+2x)$.'),
  ('h6_kettingregel', 'wortel_polynoom', 6, 3, 'Schrijf terug: $k''(x) = \dfrac{5(4x^3+x)}{\sqrt{2x^4+x^2}}$ (na vereenvoudigen $\tfrac{5}{2}(8x^3+2x) = 5(4x^3+x)$).'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 1, 1, 'Schrijf om: $\dfrac{1}{(2x+1)^2} = (2x+1)^{-2}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 1, 2, 'Pas de kettingregel toe: $u''(v) = -2v^{-3}$ en $v''(x) = 2$, geeft $f''(x) = -2(2x+1)^{-3} \cdot 2 = -4(2x+1)^{-3}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 1, 3, 'Schrijf terug: $f''(x) = -\dfrac{4}{(2x+1)^3}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 2, 1, 'Schrijf om: $\dfrac{1}{(3x-2)^3} = (3x-2)^{-3}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 2, 2, 'Pas de kettingregel toe: $u''(v) = -3v^{-4}$ en $v''(x) = 3$, geeft $f''(x) = -3(3x-2)^{-4} \cdot 3 = -9(3x-2)^{-4}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 2, 3, 'Schrijf terug: $f''(x) = -\dfrac{9}{(3x-2)^4}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 3, 1, 'Schrijf om: $\dfrac{5}{(2x^3-7x)^4} = 5(2x^3-7x)^{-4}$. Herken $v(x) = 2x^3-7x$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 3, 2, 'Bepaal $v''(x) = 6x^2-7$. Pas de kettingregel toe: $g''(x) = 5 \cdot (-4)(2x^3-7x)^{-5} \cdot (6x^2-7)$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 3, 3, 'Schrijf terug: $g''(x) = -\dfrac{20(6x^2-7)}{(2x^3-7x)^5}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 4, 1, 'Schrijf om: $\dfrac{6}{(x^2+3x)^3} = 6(x^2+3x)^{-3}$. Herken $v(x) = x^2+3x$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 4, 2, 'Bepaal $v''(x) = 2x+3$. Pas de kettingregel toe: $h''(x) = 6 \cdot (-3)(x^2+3x)^{-4} \cdot (2x+3)$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 4, 3, 'Schrijf terug: $h''(x) = -\dfrac{18(2x+3)}{(x^2+3x)^4}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 5, 1, 'Schrijf om: $\dfrac{3}{\sqrt{2x+1}} = 3(2x+1)^{-\frac{1}{2}}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 5, 2, 'Pas de kettingregel toe: $f''(x) = 3 \cdot (-\tfrac{1}{2})(2x+1)^{-\frac{3}{2}} \cdot 2 = -3(2x+1)^{-\frac{3}{2}}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 5, 3, 'Schrijf terug: $f''(x) = -\dfrac{3}{(2x+1)\sqrt{2x+1}}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 6, 1, 'Schrijf om: $\dfrac{2}{\sqrt{x^2+4}} = 2(x^2+4)^{-\frac{1}{2}}$. Herken $v(x) = x^2+4$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 6, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $k''(x) = 2 \cdot (-\tfrac{1}{2})(x^2+4)^{-\frac{3}{2}} \cdot 2x = -2x(x^2+4)^{-\frac{3}{2}}$.'),
  ('h6_kettingregel', 'negatieve_macht_expressie', 6, 3, 'Schrijf terug: $k''(x) = -\dfrac{2x}{(x^2+4)\sqrt{x^2+4}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 1, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \sqrt{2x+1} = (2x+1)^{\frac{1}{2}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 1, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \tfrac{1}{2}(2x+1)^{-\frac{1}{2}} \cdot 2 = (2x+1)^{-\frac{1}{2}}$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 1, 3, 'Pas de productregel toe: $f''(x) = 1 \cdot \sqrt{2x+1} + x \cdot \dfrac{1}{\sqrt{2x+1}} = \dfrac{(2x+1) + x}{\sqrt{2x+1}} = \dfrac{3x+1}{\sqrt{2x+1}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 2, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = (2x+1)^3$.'),
  ('h6_combinaties', 'ketting_plus_product', 2, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = 3(2x+1)^2 \cdot 2 = 6(2x+1)^2$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 2, 3, 'Pas de productregel toe: $f''(x) = (2x+1)^3 + x \cdot 6(2x+1)^2 = (2x+1)^3 + 6x(2x+1)^2$.'),
  ('h6_combinaties', 'ketting_plus_product', 3, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \sqrt{3x+1}$.'),
  ('h6_combinaties', 'ketting_plus_product', 3, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \dfrac{3}{2\sqrt{3x+1}}$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 3, 3, 'Pas de productregel toe en vereenvoudig: $g''(x) = \sqrt{3x+1} + x \cdot \dfrac{3}{2\sqrt{3x+1}} = \dfrac{2(3x+1) + 3x}{2\sqrt{3x+1}} = \dfrac{9x+2}{2\sqrt{3x+1}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 4, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = (3x+1)^3$.'),
  ('h6_combinaties', 'ketting_plus_product', 4, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = 3(3x+1)^2 \cdot 3 = 9(3x+1)^2$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 4, 3, 'Pas de productregel toe: $h''(x) = (3x+1)^3 + x \cdot 9(3x+1)^2 = (3x+1)^3 + 9x(3x+1)^2$.'),
  ('h6_combinaties', 'ketting_plus_product', 5, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = \sqrt{x+1} = (x+1)^{\frac{1}{2}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 5, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = \dfrac{1}{2\sqrt{x+1}}$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 5, 3, 'Pas de productregel toe: $f''(x) = 2x\sqrt{x+1} + x^2 \cdot \dfrac{1}{2\sqrt{x+1}}$.'),
  ('h6_combinaties', 'ketting_plus_product', 6, 1, 'Herken de productregel: $u(x) = x+1$ en $v(x) = (2x-1)^3$.'),
  ('h6_combinaties', 'ketting_plus_product', 6, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = 3(2x-1)^2 \cdot 2 = 6(2x-1)^2$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_product', 6, 3, 'Pas de productregel toe: $k''(x) = (2x-1)^3 + (x+1) \cdot 6(2x-1)^2 = (2x-1)^3 + 6(x+1)(2x-1)^2$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 1, 1, 'Benoem teller en noemer: $t(x) = x+6$ en $n(x) = \sqrt{8x+9} = (8x+9)^{\frac{1}{2}}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 1, 2, 'Bepaal $t''(x) = 1$ en $n''(x) = \dfrac{8}{2\sqrt{8x+9}} = \dfrac{4}{\sqrt{8x+9}}$ (kettingregel). Pas de quotiëntregel toe.'),
  ('h6_combinaties', 'ketting_plus_quotient', 1, 3, 'Vereenvoudig de teller: $\dfrac{\sqrt{8x+9} - (x+6) \cdot \frac{4}{\sqrt{8x+9}}}{8x+9} = \dfrac{(8x+9) - 4(x+6)}{(8x+9)\sqrt{8x+9}} = \dfrac{4x-15}{(8x+9)\sqrt{8x+9}}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 2, 1, 'Benoem: $t(x) = x$ en $n(x) = \sqrt{2x+1} = (2x+1)^{\frac{1}{2}}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 2, 2, 'Bepaal $t''(x) = 1$ en $n''(x) = \dfrac{1}{\sqrt{2x+1}}$ (kettingregel). Pas de quotiëntregel toe.'),
  ('h6_combinaties', 'ketting_plus_quotient', 2, 3, 'Vereenvoudig: $\dfrac{\sqrt{2x+1} - x \cdot \frac{1}{\sqrt{2x+1}}}{2x+1} = \dfrac{(2x+1) - x}{(2x+1)\sqrt{2x+1}} = \dfrac{x+1}{(2x+1)\sqrt{2x+1}}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 3, 1, 'Benoem: $t(x) = \sqrt{x^2+1}$ en $n(x) = 2x+1$. Bepaal $t''(x) = \dfrac{x}{\sqrt{x^2+1}}$ (kettingregel) en $n''(x) = 2$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 3, 2, 'Pas de quotiëntregel toe: $g''(x) = \dfrac{\frac{x}{\sqrt{x^2+1}} \cdot (2x+1) - \sqrt{x^2+1} \cdot 2}{(2x+1)^2}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 3, 3, 'Laat de breuk in deze vorm staan — verdere vereenvoudiging is mogelijk maar niet vereist.'),
  ('h6_combinaties', 'ketting_plus_quotient', 4, 1, 'Benoem: $t(x) = x^2-1$ en $n(x) = \sqrt{4x+1}$. Bepaal $t''(x) = 2x$ en $n''(x) = \dfrac{2}{\sqrt{4x+1}}$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_quotient', 4, 2, 'Pas de quotiëntregel toe: $h''(x) = \dfrac{2x\sqrt{4x+1} - (x^2-1) \cdot \frac{2}{\sqrt{4x+1}}}{4x+1}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 4, 3, 'Laat in deze vorm staan.'),
  ('h6_combinaties', 'ketting_plus_quotient', 5, 1, 'Benoem: $t(x) = (2x+1)^2$ en $n(x) = x+1$. Bepaal $t''(x) = 2(2x+1) \cdot 2 = 4(2x+1)$ (kettingregel) en $n''(x) = 1$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 5, 2, 'Pas de quotiëntregel toe: $f''(x) = \dfrac{4(2x+1)(x+1) - (2x+1)^2}{(x+1)^2}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 5, 3, 'Laat in deze gefactoriseerde vorm staan.'),
  ('h6_combinaties', 'ketting_plus_quotient', 6, 1, 'Benoem: $t(x) = x^2+1$ en $n(x) = (3x-2)^2$. Bepaal $t''(x) = 2x$ en $n''(x) = 2(3x-2) \cdot 3 = 6(3x-2)$ (kettingregel).'),
  ('h6_combinaties', 'ketting_plus_quotient', 6, 2, 'Pas de quotiëntregel toe: $k''(x) = \dfrac{2x(3x-2)^2 - (x^2+1) \cdot 6(3x-2)}{(3x-2)^4}$.'),
  ('h6_combinaties', 'ketting_plus_quotient', 6, 3, 'Laat in deze vorm staan.')
) AS s(topic_slug, cluster_slug, q_order, step_order, description)
JOIN public.topics_new t          ON t.slug    = s.topic_slug
JOIN public.topic_clusters_new tc ON tc.slug   = s.cluster_slug AND tc.topic_id = t.id
JOIN public.questions_new q       ON q.cluster_id = tc.id AND q.order_index = s.q_order;

-- Validatie
SELECT 'question_steps_new' AS tbl, COUNT(*)::text AS n FROM public.question_steps_new;
-- Verwacht: 184 (H2) + 198 (H6) = 382

COMMIT;
