-- =============================================================================
-- Migration 0016: H7 question steps
-- =============================================================================
-- Inserts 119 question steps for H7 into question_steps_new.
-- Questions matched by topic_slug + cluster_slug + order_index.
-- =============================================================================

BEGIN;

INSERT INTO public.question_steps_new (question_id, step_order, step_description)
SELECT q.id, s.step_order, s.description
FROM (VALUES
  ('h7_goniometrie_diff', 'basis_sin_cos', 1, 1, 'Gebruik de basisregel: $[\sin(x)]'' = \cos(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 1, 2, '$f''(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 2, 1, 'Gebruik de basisregel: $[\cos(x)]'' = -\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 2, 2, '$f''(x) = -\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 3, 1, 'Differentieer termsgewijs met de somregel.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 3, 2, '$[3\sin(x)]'' = 3\cos(x)$ en $[2\cos(x)]'' = -2\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 3, 3, 'Combineer: $f''(x) = 3\cos(x) - 2\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 4, 1, 'Differentieer termsgewijs: $[x^2]'' = 2x$ en $[-\cos(x)]'' = \sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 4, 2, 'Combineer: $f''(x) = 2x + \sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 5, 1, 'Differentieer termsgewijs: $[5x]'' = 5$, $[4\sin(x)]'' = 4\cos(x)$ en $[-3\cos(x)]'' = 3\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 5, 2, 'Combineer: $f''(x) = 5 + 4\cos(x) + 3\sin(x)$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 6, 1, 'Merk op: $\cos(\tfrac{1}{2}\pi) = 0$, dus $2x\cos(\tfrac{1}{2}\pi) = 0$. De term $-2x\cos(\tfrac{1}{2}\pi)$ is gewoon $0$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 6, 2, 'Differentieer: $[\tfrac{1}{2}\sin(x)]'' = \tfrac{1}{2}\cos(x)$ en $[0]'' = 0$.'),
  ('h7_goniometrie_diff', 'basis_sin_cos', 6, 3, 'Antwoord: $f''(x) = \tfrac{1}{2}\cos(x)$.'),
  ('h7_goniometrie_diff', 'basis_tan', 1, 1, 'Gebruik de basisregel: $[\tan(x)]'' = \dfrac{1}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 1, 2, '$f''(x) = \dfrac{1}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 2, 1, 'Gebruik de basisregel met constante factor: $[2\tan(x)]'' = 2 \cdot \dfrac{1}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 2, 2, '$f''(x) = \dfrac{2}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 3, 1, 'Differentieer termsgewijs: $[\tan(x)]'' = \dfrac{1}{\cos^2(x)}$ en $[x]'' = 1$.'),
  ('h7_goniometrie_diff', 'basis_tan', 3, 2, 'Combineer: $f''(x) = \dfrac{1}{\cos^2(x)} + 1$.'),
  ('h7_goniometrie_diff', 'basis_tan', 4, 1, 'Herken de samengestelde functie: $3\tan(2x)$ — buitenste is $\tan$, binnenste is $2x$.'),
  ('h7_goniometrie_diff', 'basis_tan', 4, 2, 'Pas de kettingregel toe: $[\tan(2x)]'' = \dfrac{1}{\cos^2(2x)} \cdot 2$.'),
  ('h7_goniometrie_diff', 'basis_tan', 4, 3, 'Antwoord: $f''(x) = \dfrac{6}{\cos^2(2x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 5, 1, 'Herken de samengestelde functie: buitenste is $\tan$, binnenste is $x^3$.'),
  ('h7_goniometrie_diff', 'basis_tan', 5, 2, 'Pas de kettingregel toe: $[\tan(x^3)]'' = \dfrac{1}{\cos^2(x^3)} \cdot 3x^2$.'),
  ('h7_goniometrie_diff', 'basis_tan', 5, 3, 'Antwoord: $f''(x) = \dfrac{3x^2}{\cos^2(x^3)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 6, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \tan(x)$.'),
  ('h7_goniometrie_diff', 'basis_tan', 6, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \dfrac{1}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'basis_tan', 6, 3, 'Pas de productregel toe: $f''(x) = \tan(x) + \dfrac{x}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 1, 1, 'Herken de samengestelde functie: buitenste is $\sin$, binnenste is $2x$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 1, 2, 'Pas de kettingregel toe: $[\sin(2x)]'' = \cos(2x) \cdot 2$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 1, 3, 'Antwoord: $f''(x) = 2\cos(2x)$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 2, 1, 'Herken de samengestelde functie: buitenste is $\cos$, binnenste is $3x$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 2, 2, 'Pas de kettingregel toe: $[\cos(3x)]'' = -\sin(3x) \cdot 3$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 2, 3, 'Antwoord: $f''(x) = -3\sin(3x)$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 3, 1, 'Herken: buitenste is $\sin$, binnenste is $2x+1$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 3, 2, 'Pas de kettingregel toe: $[\sin(2x+1)]'' = \cos(2x+1) \cdot 2$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 3, 3, 'Antwoord: $f''(x) = 2\cos(2x+1)$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 4, 1, 'De $3$ heeft afgeleide $0$. Herken: buitenste is $4\sin$, binnenste is $2x - \tfrac{1}{4}\pi$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 4, 2, 'Pas de kettingregel toe: $[4\sin(2x-\tfrac{1}{4}\pi)]'' = 4\cos(2x-\tfrac{1}{4}\pi) \cdot 2$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 4, 3, 'Antwoord: $f''(x) = 8\cos(2x - \tfrac{1}{4}\pi)$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 5, 1, 'De $10$ heeft afgeleide $0$. Herken: buitenste is $16\cos$, binnenste is $\tfrac{1}{2}(x-1)$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 5, 2, 'Pas de kettingregel toe: $[16\cos(\tfrac{1}{2}(x-1))]'' = -16\sin(\tfrac{1}{2}(x-1)) \cdot \tfrac{1}{2}$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 5, 3, 'Antwoord: $g''(x) = -8\sin(\tfrac{1}{2}(x-1))$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 6, 1, 'De $1$ heeft afgeleide $0$. Herken: buitenste is $2\cos$, binnenste is $3(x - \tfrac{1}{6}\pi) = 3x - \tfrac{1}{2}\pi$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 6, 2, 'Pas de kettingregel toe: $[2\cos(3x-\tfrac{1}{2}\pi)]'' = -2\sin(3x-\tfrac{1}{2}\pi) \cdot 3$.'),
  ('h7_goniometrie_diff', 'ketting_lineair', 6, 3, 'Antwoord: $f''(x) = -6\sin(3x - \tfrac{1}{2}\pi)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 1, 1, 'Herken: buitenste is $\sin$, binnenste $v(x) = x^2$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 1, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $[\sin(x^2)]'' = \cos(x^2) \cdot 2x$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 1, 3, 'Antwoord: $f''(x) = 2x\cos(x^2)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 2, 1, 'Herken: buitenste is $\cos$, binnenste $v(x) = x^3$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 2, 2, 'Bepaal $v''(x) = 3x^2$. Pas de kettingregel toe: $[\cos(x^3)]'' = -\sin(x^3) \cdot 3x^2$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 2, 3, 'Antwoord: $f''(x) = -3x^2\sin(x^3)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 3, 1, 'Herken: buitenste is $\sin$, binnenste $v(x) = x^2+1$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 3, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $[\sin(x^2+1)]'' = \cos(x^2+1) \cdot 2x$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 3, 3, 'Antwoord: $f''(x) = 2x\cos(x^2+1)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 4, 1, 'Herken: buitenste is $\cos$, binnenste $v(x) = x^4$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 4, 2, 'Bepaal $v''(x) = 4x^3$. Pas de kettingregel toe: $[\cos(x^4)]'' = -\sin(x^4) \cdot 4x^3$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 4, 3, 'Antwoord: $f''(x) = -4x^3\sin(x^4)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 5, 1, 'Herken: buitenste is $\sin$, binnenste $v(x) = x^2+2x$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 5, 2, 'Bepaal $v''(x) = 2x+2$. Pas de kettingregel toe: $[\sin(x^2+2x)]'' = \cos(x^2+2x) \cdot (2x+2)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 5, 3, 'Antwoord: $g''(x) = (2x+2)\cos(x^2+2x)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 6, 1, 'Herken: buitenste is $3\cos$, binnenste $v(x) = x^2-5x+1$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 6, 2, 'Bepaal $v''(x) = 2x-5$. Pas de kettingregel toe: $[3\cos(x^2-5x+1)]'' = -3\sin(x^2-5x+1) \cdot (2x-5)$.'),
  ('h7_goniometrie_diff', 'ketting_polynoom', 6, 3, 'Antwoord: $h''(x) = -3(2x-5)\sin(x^2-5x+1)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 1, 1, 'Herken: buitenste is $(\cdot)^2$, binnenste $v(x) = \sin(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 1, 2, 'Bepaal $v''(x) = \cos(x)$. Pas de kettingregel toe: $[\sin^2(x)]'' = 2\sin(x) \cdot \cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 1, 3, 'Antwoord: $f''(x) = 2\sin(x)\cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 2, 1, 'Herken: buitenste is $(\cdot)^2$, binnenste $v(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 2, 2, 'Bepaal $v''(x) = -\sin(x)$. Pas de kettingregel toe: $[\cos^2(x)]'' = 2\cos(x) \cdot (-\sin(x))$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 2, 3, 'Antwoord: $f''(x) = -2\sin(x)\cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 3, 1, 'Herken: $2\sin^2(x)$ — buitenste is $2(\cdot)^2$, binnenste $v(x) = \sin(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 3, 2, 'Bepaal $v''(x) = \cos(x)$. Pas de kettingregel toe: $[2\sin^2(x)]'' = 2 \cdot 2\sin(x) \cdot \cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 3, 3, 'Antwoord: $g''(x) = 4\sin(x)\cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 4, 1, 'Herken: buitenste is $(\cdot)^3$, binnenste $v(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 4, 2, 'Bepaal $v''(x) = -\sin(x)$. Pas de kettingregel toe: $[\cos^3(x)]'' = 3\cos^2(x) \cdot (-\sin(x))$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 4, 3, 'Antwoord: $h''(x) = -3\cos^2(x)\sin(x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 5, 1, 'Herken: $\sin^3(2x)$ — twee keer kettingregel nodig. Buitenste: $(\cdot)^3$, middelste: $\sin$, binnenste: $2x$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 5, 2, 'Pas kettingregel stap voor stap toe: $[\sin^3(2x)]'' = 3\sin^2(2x) \cdot [\sin(2x)]'' = 3\sin^2(2x) \cdot \cos(2x) \cdot 2$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 5, 3, 'Antwoord: $f''(x) = 6\sin^2(2x)\cos(2x)$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 6, 1, 'Herken: $\cos^2(2x)$ — buitenste: $(\cdot)^2$, middelste: $\cos$, binnenste: $2x$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 6, 2, 'Pas kettingregel toe: $[\cos^2(2x)]'' = 2\cos(2x) \cdot [-\sin(2x)] \cdot 2$.'),
  ('h7_goniometrie_diff', 'macht_van_gonio', 6, 3, 'Antwoord: $j''(x) = -4\cos(2x)\sin(2x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 1, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 1, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 1, 3, 'Pas de productregel toe: $f''(x) = \sin(x) + x\cos(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 2, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 2, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = -\sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 2, 3, 'Pas de productregel toe: $f''(x) = \cos(x) - x\sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 3, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \cos(2x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 3, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = -2\sin(2x)$ (kettingregel).'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 3, 3, 'Pas de productregel toe: $g''(x) = \cos(2x) - 2x\sin(2x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 4, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = \sin(3x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 4, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = 3\cos(3x)$ (kettingregel).'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 4, 3, 'Pas de productregel toe: $h''(x) = 2x\sin(3x) + 3x^2\cos(3x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 5, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = \tan(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 5, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = \dfrac{1}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 5, 3, 'Pas de productregel toe: $j''(x) = 2x\tan(x) + \dfrac{x^2}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 6, 1, 'Herken de productregel: $u(x) = 2x$ en $v(x) = \sin(3x-1)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 6, 2, 'Bepaal $u''(x) = 2$ en $v''(x) = 3\cos(3x-1)$ (kettingregel).'),
  ('h7_goniometrie_diff', 'gonio_plus_product', 6, 3, 'Pas de productregel toe: $k''(x) = 2\sin(3x-1) + 2x \cdot 3\cos(3x-1) = 2\sin(3x-1) + 6x\cos(3x-1)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 1, 1, 'Benoem: $t(x) = \sin(x)$ en $n(x) = x$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 1, 2, 'Bepaal $t''(x) = \cos(x)$ en $n''(x) = 1$. Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 1, 3, '$f''(x) = \dfrac{x\cos(x) - \sin(x)}{x^2}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 2, 1, 'Benoem: $t(x) = \cos(x)$ en $n(x) = \sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 2, 2, 'Bepaal $t''(x) = -\sin(x)$ en $n''(x) = \cos(x)$. Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 2, 3, '$f''(x) = \dfrac{-\sin(x)\sin(x) - \cos(x)\cos(x)}{\sin^2(x)} = \dfrac{-1}{\sin^2(x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 3, 1, 'Benoem: $t(x) = x + \cos(x)$ en $n(x) = \sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 3, 2, 'Bepaal $t''(x) = 1 - \sin(x)$ en $n''(x) = \cos(x)$. Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 3, 3, '$g''(x) = \dfrac{(1-\sin(x))\sin(x) - (x+\cos(x))\cos(x)}{\sin^2(x)} = \dfrac{\sin(x) - x\cos(x) - 1}{\sin^2(x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 4, 1, 'Benoem: $t(x) = x^2 + \sin(x)$ en $n(x) = \cos(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 4, 2, 'Bepaal $t''(x) = 2x + \cos(x)$ en $n''(x) = -\sin(x)$. Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 4, 3, '$h''(x) = \dfrac{(2x+\cos(x))\cos(x) - (x^2+\sin(x))(-\sin(x))}{\cos^2(x)} = \dfrac{(2x+\cos(x))\cos(x) + (x^2+\sin(x))\sin(x)}{\cos^2(x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 5, 1, 'Benoem: $t(x) = \cos(3x)$ en $n(x) = \sin(3x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 5, 2, 'Bepaal $t''(x) = -3\sin(3x)$ en $n''(x) = 3\cos(3x)$ (kettingregel). Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 5, 3, '$f''(x) = \dfrac{-3\sin(3x)\sin(3x) - \cos(3x) \cdot 3\cos(3x)}{\sin^2(3x)} = \dfrac{-3}{\sin^2(3x)}$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 6, 1, 'Benoem: $t(x) = \cos(x)$ en $n(x) = 1 - \sin(x)$.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 6, 2, 'Bepaal $t''(x) = -\sin(x)$ en $n''(x) = -\cos(x)$. Pas de quotiëntregel toe.'),
  ('h7_goniometrie_diff', 'gonio_plus_quotient', 6, 3, '$k''(x) = \dfrac{-\sin(x)(1-\sin(x)) - \cos(x)(-\cos(x))}{(1-\sin(x))^2} = \dfrac{-\sin(x)+\sin^2(x)+\cos^2(x)}{(1-\sin(x))^2} = \dfrac{1-\sin(x)}{(1-\sin(x))^2} = \dfrac{1}{1-\sin(x)}$.')
) AS s(topic_slug, cluster_slug, q_order, step_order, description)
JOIN public.topics_new t          ON t.slug    = s.topic_slug
JOIN public.topic_clusters_new tc ON tc.slug   = s.cluster_slug AND tc.topic_id = t.id
JOIN public.questions_new q       ON q.cluster_id = tc.id AND q.order_index = s.q_order;

-- Validatie
SELECT 'question_steps_new' AS tbl, COUNT(*)::text AS n FROM public.question_steps_new;
-- Verwacht: 184 (H2) + 198 (H6) + 119 (H7) = 501

COMMIT;
