-- =============================================================================
-- Migration 0017: H9 question steps
-- =============================================================================
-- Inserts 162 question steps for H9 into question_steps_new.
-- Questions matched by topic_slug + cluster_slug + order_index.
-- =============================================================================

BEGIN;

INSERT INTO public.question_steps_new (question_id, step_order, step_description)
SELECT q.id, s.step_order, s.description
FROM (VALUES
  ('h9_e_machten', 'basis_ex', 1, 1, 'Gebruik de basisregel: $[e^x]'' = e^x$.'),
  ('h9_e_machten', 'basis_ex', 1, 2, '$f''(x) = e^x$.'),
  ('h9_e_machten', 'basis_ex', 2, 1, 'Differentieer termsgewijs: $[e^x]'' = e^x$ en $[2]'' = 0$.'),
  ('h9_e_machten', 'basis_ex', 2, 2, '$f''(x) = e^x$.'),
  ('h9_e_machten', 'basis_ex', 3, 1, 'Gebruik de basisregel met constante factor: $[3e^x]'' = 3e^x$.'),
  ('h9_e_machten', 'basis_ex', 3, 2, '$f''(x) = 3e^x$.'),
  ('h9_e_machten', 'basis_ex', 4, 1, 'Differentieer termsgewijs: $[2e^x]'' = 2e^x$ en $\left[\dfrac{1}{x}\right]'' = [x^{-1}]'' = -x^{-2}$.'),
  ('h9_e_machten', 'basis_ex', 4, 2, 'Schrijf terug: $g''(x) = 2e^x - \dfrac{1}{x^2}$.'),
  ('h9_e_machten', 'basis_ex', 5, 1, 'Differentieer termsgewijs: $[e^x]'' = e^x$ en $[-4x^3]'' = -12x^2$.'),
  ('h9_e_machten', 'basis_ex', 5, 2, '$h''(x) = e^x - 12x^2$.'),
  ('h9_e_machten', 'basis_ex', 6, 1, 'Differentieer termsgewijs: $[3e^x]'' = 3e^x$ en $\left[\dfrac{1}{x^2}\right]'' = [x^{-2}]'' = -2x^{-3}$.'),
  ('h9_e_machten', 'basis_ex', 6, 2, 'Schrijf terug: $f''(x) = 3e^x - \dfrac{2}{x^3}$.'),
  ('h9_e_machten', 'ketting_lineair', 1, 1, 'Herken de samengestelde functie: buitenste is $e^{(\cdot)}$, binnenste $v(x) = 2x$.'),
  ('h9_e_machten', 'ketting_lineair', 1, 2, 'Bepaal $v''(x) = 2$. Pas de kettingregel toe: $[e^{2x}]'' = e^{2x} \cdot 2$.'),
  ('h9_e_machten', 'ketting_lineair', 1, 3, 'Antwoord: $f''(x) = 2e^{2x}$.'),
  ('h9_e_machten', 'ketting_lineair', 2, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = 3x$.'),
  ('h9_e_machten', 'ketting_lineair', 2, 2, 'Bepaal $v''(x) = 3$. Pas de kettingregel toe: $[e^{3x}]'' = e^{3x} \cdot 3$.'),
  ('h9_e_machten', 'ketting_lineair', 2, 3, 'Antwoord: $f''(x) = 3e^{3x}$.'),
  ('h9_e_machten', 'ketting_lineair', 3, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = 2x+3$.'),
  ('h9_e_machten', 'ketting_lineair', 3, 2, 'Bepaal $v''(x) = 2$. Pas de kettingregel toe: $[e^{2x+3}]'' = e^{2x+3} \cdot 2$.'),
  ('h9_e_machten', 'ketting_lineair', 3, 3, 'Antwoord: $f''(x) = 2e^{2x+3}$.'),
  ('h9_e_machten', 'ketting_lineair', 4, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = -x$.'),
  ('h9_e_machten', 'ketting_lineair', 4, 2, 'Bepaal $v''(x) = -1$. Pas de kettingregel toe: $[e^{-x}]'' = e^{-x} \cdot (-1)$.'),
  ('h9_e_machten', 'ketting_lineair', 4, 3, 'Antwoord: $f''(x) = -e^{-x}$.'),
  ('h9_e_machten', 'ketting_lineair', 5, 1, 'Herken: buitenste is $4e^{(\cdot)}$, binnenste $v(x) = -2x$.'),
  ('h9_e_machten', 'ketting_lineair', 5, 2, 'Bepaal $v''(x) = -2$. Pas de kettingregel toe: $[4e^{-2x}]'' = 4e^{-2x} \cdot (-2)$.'),
  ('h9_e_machten', 'ketting_lineair', 5, 3, 'Antwoord: $f''(x) = -8e^{-2x}$.'),
  ('h9_e_machten', 'ketting_lineair', 6, 1, 'Differentieer termsgewijs. Voor $5e^{2x}$: binnenste $v = 2x$, $v'' = 2$, geeft $10e^{2x}$.'),
  ('h9_e_machten', 'ketting_lineair', 6, 2, 'Voor $-3e^{-2x}$: binnenste $v = -2x$, $v'' = -2$, geeft $-3 \cdot (-2) \cdot e^{-2x} = 6e^{-2x}$.'),
  ('h9_e_machten', 'ketting_lineair', 6, 3, 'Antwoord: $g''(x) = 10e^{2x} + 6e^{-2x}$.'),
  ('h9_e_machten', 'ketting_polynoom', 1, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = x^2$.'),
  ('h9_e_machten', 'ketting_polynoom', 1, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $[e^{x^2}]'' = e^{x^2} \cdot 2x$.'),
  ('h9_e_machten', 'ketting_polynoom', 1, 3, 'Antwoord: $f''(x) = 2x \cdot e^{x^2}$.'),
  ('h9_e_machten', 'ketting_polynoom', 2, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = x^2+1$.'),
  ('h9_e_machten', 'ketting_polynoom', 2, 2, 'Bepaal $v''(x) = 2x$. Pas de kettingregel toe: $[e^{x^2+1}]'' = e^{x^2+1} \cdot 2x$.'),
  ('h9_e_machten', 'ketting_polynoom', 2, 3, 'Antwoord: $f''(x) = 2x \cdot e^{x^2+1}$.'),
  ('h9_e_machten', 'ketting_polynoom', 3, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = x^2+x$.'),
  ('h9_e_machten', 'ketting_polynoom', 3, 2, 'Bepaal $v''(x) = 2x+1$. Pas de kettingregel toe: $[e^{x^2+x}]'' = e^{x^2+x} \cdot (2x+1)$.'),
  ('h9_e_machten', 'ketting_polynoom', 3, 3, 'Antwoord: $f''(x) = (2x+1)e^{x^2+x}$.'),
  ('h9_e_machten', 'ketting_polynoom', 4, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = x^3$.'),
  ('h9_e_machten', 'ketting_polynoom', 4, 2, 'Bepaal $v''(x) = 3x^2$. Pas de kettingregel toe: $[e^{x^3}]'' = e^{x^3} \cdot 3x^2$.'),
  ('h9_e_machten', 'ketting_polynoom', 4, 3, 'Antwoord: $g''(x) = 3x^2 \cdot e^{x^3}$.'),
  ('h9_e_machten', 'ketting_polynoom', 5, 1, 'Herken: buitenste is $3e^{(\cdot)}$, binnenste $v(x) = x^2+2x$.'),
  ('h9_e_machten', 'ketting_polynoom', 5, 2, 'Bepaal $v''(x) = 2x+2$. Pas de kettingregel toe: $[3e^{x^2+2x}]'' = 3e^{x^2+2x} \cdot (2x+2)$.'),
  ('h9_e_machten', 'ketting_polynoom', 5, 3, 'Antwoord: $h''(x) = 3(2x+2)e^{x^2+2x}$.'),
  ('h9_e_machten', 'ketting_polynoom', 6, 1, 'Herken: buitenste is $e^{(\cdot)}$, binnenste $v(x) = -x^2$.'),
  ('h9_e_machten', 'ketting_polynoom', 6, 2, 'Bepaal $v''(x) = -2x$. Pas de kettingregel toe: $[e^{-x^2}]'' = e^{-x^2} \cdot (-2x)$.'),
  ('h9_e_machten', 'ketting_polynoom', 6, 3, 'Antwoord: $f''(x) = -2x \cdot e^{-x^2}$.'),
  ('h9_e_machten', 'e_plus_product', 1, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 1, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 1, 3, 'Pas de productregel toe: $f''(x) = e^x + x \cdot e^x = (1+x)e^x$.'),
  ('h9_e_machten', 'e_plus_product', 2, 1, 'Herken de productregel: $u(x) = x+1$ en $v(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 2, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 2, 3, 'Pas de productregel toe: $f''(x) = e^x + (x+1)e^x = (2+x)e^x$.'),
  ('h9_e_machten', 'e_plus_product', 3, 1, 'Herken de productregel: $u(x) = x^2+2$ en $v(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 3, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 3, 3, 'Pas de productregel toe: $g''(x) = 2x \cdot e^x + (x^2+2)e^x = (x^2+2x+2)e^x$.'),
  ('h9_e_machten', 'e_plus_product', 4, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 4, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_product', 4, 3, 'Pas de productregel toe: $f''(x) = 2x \cdot e^x + x^2 \cdot e^x = (2x+x^2)e^x$.'),
  ('h9_e_machten', 'e_plus_product', 5, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = e^{2x+3}$.'),
  ('h9_e_machten', 'e_plus_product', 5, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = 2e^{2x+3}$ (kettingregel).'),
  ('h9_e_machten', 'e_plus_product', 5, 3, 'Pas de productregel toe: $h''(x) = e^{2x+3} + x \cdot 2e^{2x+3} = (1+2x)e^{2x+3}$.'),
  ('h9_e_machten', 'e_plus_product', 6, 1, 'Herken de productregel: $u(x) = 3x$ en $v(x) = e^{2x-1}$.'),
  ('h9_e_machten', 'e_plus_product', 6, 2, 'Bepaal $u''(x) = 3$ en $v''(x) = 2e^{2x-1}$ (kettingregel).'),
  ('h9_e_machten', 'e_plus_product', 6, 3, 'Pas de productregel toe: $k''(x) = 3e^{2x-1} + 3x \cdot 2e^{2x-1} = (3+6x)e^{2x-1}$.'),
  ('h9_e_machten', 'e_plus_quotient', 1, 1, 'Benoem: $t(x) = x$ en $n(x) = e^x$.'),
  ('h9_e_machten', 'e_plus_quotient', 1, 2, 'Bepaal $t''(x) = 1$ en $n''(x) = e^x$. Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 1, 3, '$f''(x) = \dfrac{e^x - x \cdot e^x}{e^{2x}} = \dfrac{(1-x)e^x}{e^{2x}} = \dfrac{1-x}{e^x}$.'),
  ('h9_e_machten', 'e_plus_quotient', 2, 1, 'Benoem: $t(x) = e^x$ en $n(x) = x$.'),
  ('h9_e_machten', 'e_plus_quotient', 2, 2, 'Bepaal $t''(x) = e^x$ en $n''(x) = 1$. Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 2, 3, '$f''(x) = \dfrac{e^x \cdot x - e^x \cdot 1}{x^2} = \dfrac{(x-1)e^x}{x^2}$.'),
  ('h9_e_machten', 'e_plus_quotient', 3, 1, 'Benoem: $t(x) = 2e^x$ en $n(x) = x-1$.'),
  ('h9_e_machten', 'e_plus_quotient', 3, 2, 'Bepaal $t''(x) = 2e^x$ en $n''(x) = 1$. Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 3, 3, '$g''(x) = \dfrac{2e^x(x-1) - 2e^x}{(x-1)^2} = \dfrac{2e^x(x-2)}{(x-1)^2}$.'),
  ('h9_e_machten', 'e_plus_quotient', 4, 1, 'Benoem: $t(x) = x^3$ en $n(x) = e^{x^2}$.'),
  ('h9_e_machten', 'e_plus_quotient', 4, 2, 'Bepaal $t''(x) = 3x^2$ en $n''(x) = 2x \cdot e^{x^2}$ (kettingregel). Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 4, 3, '$f''(x) = \dfrac{3x^2 \cdot e^{x^2} - x^3 \cdot 2x \cdot e^{x^2}}{e^{2x^2}} = \dfrac{(3x^2-2x^4)e^{x^2}}{e^{2x^2}} = \dfrac{3x^2-2x^4}{e^{x^2}}$.'),
  ('h9_e_machten', 'e_plus_quotient', 5, 1, 'Benoem: $t(x) = 2e^{-x-1}$ en $n(x) = x^2$.'),
  ('h9_e_machten', 'e_plus_quotient', 5, 2, 'Bepaal $t''(x) = -2e^{-x-1}$ (kettingregel) en $n''(x) = 2x$. Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 5, 3, '$h''(x) = \dfrac{-2e^{-x-1} \cdot x^2 - 2e^{-x-1} \cdot 2x}{x^4} = \dfrac{-2e^{-x-1}(x^2+2x)}{x^4} = -\dfrac{2(x+2)e^{-x-1}}{x^3}$.'),
  ('h9_e_machten', 'e_plus_quotient', 6, 1, 'Benoem: $t(x) = e^{2x}$ en $n(x) = e^{2x}+1$.'),
  ('h9_e_machten', 'e_plus_quotient', 6, 2, 'Bepaal $t''(x) = 2e^{2x}$ en $n''(x) = 2e^{2x}$ (kettingregel). Pas de quotiëntregel toe.'),
  ('h9_e_machten', 'e_plus_quotient', 6, 3, '$k''(x) = \dfrac{2e^{2x}(e^{2x}+1) - e^{2x} \cdot 2e^{2x}}{(e^{2x}+1)^2} = \dfrac{2e^{2x}}{(e^{2x}+1)^2}$.'),
  ('h9_logaritmes', 'basis_ln', 1, 1, 'Gebruik de basisregel: $[\ln(x)]'' = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 1, 2, '$f''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 2, 1, 'Gebruik de basisregel met constante factor: $[2\ln(x)]'' = \dfrac{2}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 2, 2, '$f''(x) = \dfrac{2}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 3, 1, 'Gebruik de logaritme-rekenregel: $\ln(2x) = \ln(2) + \ln(x)$.'),
  ('h9_logaritmes', 'basis_ln', 3, 2, 'Differentieer: $[\ln(2)]'' = 0$ en $[\ln(x)]'' = \dfrac{1}{x}$. Antwoord: $f''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 4, 1, 'Gebruik de logaritme-rekenregel: $\ln(x\sqrt{2}) = \ln(x) + \ln(\sqrt{2})$.'),
  ('h9_logaritmes', 'basis_ln', 4, 2, '$\ln(\sqrt{2})$ is een constante, dus afgeleide is $0$. Antwoord: $g''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 5, 1, 'Differentieer termsgewijs: $[3\ln(x)]'' = \dfrac{3}{x}$ en $[2x]'' = 2$.'),
  ('h9_logaritmes', 'basis_ln', 5, 2, 'Antwoord: $h''(x) = \dfrac{3}{x} + 2$.'),
  ('h9_logaritmes', 'basis_ln', 6, 1, 'Differentieer termsgewijs: $[x]'' = 1$ en $[-\ln(x)]'' = -\dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_ln', 6, 2, 'Antwoord: $f''(x) = 1 - \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'basis_gx_glog', 1, 1, 'Gebruik de regel: $[g^x]'' = g^x \cdot \ln(g)$ met grondtal $g = 2$.'),
  ('h9_logaritmes', 'basis_gx_glog', 1, 2, '$f''(x) = 2^x \cdot \ln(2)$.'),
  ('h9_logaritmes', 'basis_gx_glog', 2, 1, 'Gebruik de regel: $[g^x]'' = g^x \cdot \ln(g)$ met grondtal $g = 3$.'),
  ('h9_logaritmes', 'basis_gx_glog', 2, 2, '$f''(x) = 3^x \cdot \ln(3)$.'),
  ('h9_logaritmes', 'basis_gx_glog', 3, 1, 'Gebruik de regel: $[{}^g\!\log(x)]'' = \dfrac{1}{x\ln(g)}$ met grondtal $g = 2$.'),
  ('h9_logaritmes', 'basis_gx_glog', 3, 2, '$f''(x) = \dfrac{1}{x\ln(2)}$.'),
  ('h9_logaritmes', 'basis_gx_glog', 4, 1, 'Gebruik de regel: $[{}^g\!\log(x)]'' = \dfrac{1}{x\ln(g)}$ met grondtal $g = 3$.'),
  ('h9_logaritmes', 'basis_gx_glog', 4, 2, '$f''(x) = \dfrac{1}{x\ln(3)}$.'),
  ('h9_logaritmes', 'basis_gx_glog', 5, 1, 'Herken: buitenste is $3^{(\cdot)}$, binnenste $v(x) = 2x-1$.'),
  ('h9_logaritmes', 'basis_gx_glog', 5, 2, 'Bepaal $v''(x) = 2$. Pas de kettingregel toe: $[3^{2x-1}]'' = 3^{2x-1} \cdot \ln(3) \cdot 2$.'),
  ('h9_logaritmes', 'basis_gx_glog', 5, 3, 'Antwoord: $g''(x) = 2 \cdot 3^{2x-1}\ln(3)$.'),
  ('h9_logaritmes', 'basis_gx_glog', 6, 1, 'Herken: ${}^3\!\log(x^2+1)$ — de logaritme heeft een samengesteld argument $v(x) = x^2+1$.'),
  ('h9_logaritmes', 'basis_gx_glog', 6, 2, 'Gebruik de kettingregel: $[{}^3\!\log(v)]'' = \dfrac{v''}{v \cdot \ln(3)}$ met $v''(x) = 2x$.'),
  ('h9_logaritmes', 'basis_gx_glog', 6, 3, 'Antwoord: $h''(x) = \dfrac{2x}{(x^2+1)\ln(3)}$.'),
  ('h9_logaritmes', 'ln_ketting', 1, 1, 'Gebruik de logaritme-rekenregel: $\ln(x^2) = 2\ln(x)$.'),
  ('h9_logaritmes', 'ln_ketting', 1, 2, 'Differentieer: $[2\ln(x)]'' = \dfrac{2}{x}$. Antwoord: $f''(x) = \dfrac{2}{x}$.'),
  ('h9_logaritmes', 'ln_ketting', 2, 1, 'Herken: buitenste is $\ln$, binnenste $v(x) = x^2+1$.'),
  ('h9_logaritmes', 'ln_ketting', 2, 2, 'Gebruik de kettingregel: $[\ln(v)]'' = \dfrac{v''}{v}$ met $v''(x) = 2x$.'),
  ('h9_logaritmes', 'ln_ketting', 2, 3, 'Antwoord: $f''(x) = \dfrac{2x}{x^2+1}$.'),
  ('h9_logaritmes', 'ln_ketting', 3, 1, 'Herken: buitenste is $\ln$, binnenste $v(x) = 2x+5$.'),
  ('h9_logaritmes', 'ln_ketting', 3, 2, 'Gebruik de kettingregel: $[\ln(2x+5)]'' = \dfrac{2}{2x+5}$.'),
  ('h9_logaritmes', 'ln_ketting', 3, 3, 'Antwoord: $g''(x) = \dfrac{2}{2x+5}$.'),
  ('h9_logaritmes', 'ln_ketting', 4, 1, 'Gebruik de logaritme-rekenregel: $\ln(\sqrt{x}) = \tfrac{1}{2}\ln(x)$.'),
  ('h9_logaritmes', 'ln_ketting', 4, 2, 'Differentieer: $\left[\tfrac{1}{2}\ln(x)\right]'' = \dfrac{1}{2x}$. Antwoord: $h''(x) = \dfrac{1}{2x}$.'),
  ('h9_logaritmes', 'ln_ketting', 5, 1, 'Herken: buitenste is $\ln$, binnenste $v(x) = x^2+3x+2$.'),
  ('h9_logaritmes', 'ln_ketting', 5, 2, 'Gebruik de kettingregel: $[\ln(v)]'' = \dfrac{v''}{v}$ met $v''(x) = 2x+3$.'),
  ('h9_logaritmes', 'ln_ketting', 5, 3, 'Antwoord: $f''(x) = \dfrac{2x+3}{x^2+3x+2}$.'),
  ('h9_logaritmes', 'ln_ketting', 6, 1, 'Herken: buitenste is $\ln$, binnenste $v(x) = x^3+1$.'),
  ('h9_logaritmes', 'ln_ketting', 6, 2, 'Gebruik de kettingregel: $[\ln(v)]'' = \dfrac{v''}{v}$ met $v''(x) = 3x^2$.'),
  ('h9_logaritmes', 'ln_ketting', 6, 3, 'Antwoord: $k''(x) = \dfrac{3x^2}{x^3+1}$.'),
  ('h9_logaritmes', 'ln_plus_product', 1, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_product', 1, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'ln_plus_product', 1, 3, 'Pas de productregel toe: $f''(x) = \ln(x) + x \cdot \dfrac{1}{x} = \ln(x) + 1$.'),
  ('h9_logaritmes', 'ln_plus_product', 2, 1, 'Herken de productregel: $u(x) = 2x$ en $v(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_product', 2, 2, 'Bepaal $u''(x) = 2$ en $v''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'ln_plus_product', 2, 3, 'Pas de productregel toe: $f''(x) = 2\ln(x) + 2x \cdot \dfrac{1}{x} = 2\ln(x) + 2$.'),
  ('h9_logaritmes', 'ln_plus_product', 3, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_product', 3, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'ln_plus_product', 3, 3, 'Pas de productregel toe: $g''(x) = 2x\ln(x) + x^2 \cdot \dfrac{1}{x} = 2x\ln(x) + x$.'),
  ('h9_logaritmes', 'ln_plus_product', 4, 1, 'Herken de productregel: $u(x) = x+1$ en $v(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_product', 4, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \dfrac{1}{x}$.'),
  ('h9_logaritmes', 'ln_plus_product', 4, 3, 'Pas de productregel toe: $h''(x) = \ln(x) + (x+1) \cdot \dfrac{1}{x} = \ln(x) + \dfrac{x+1}{x}$.'),
  ('h9_logaritmes', 'ln_plus_product', 5, 1, 'Herken de productregel: $u(x) = x^2$ en $v(x) = \ln(2x)$.'),
  ('h9_logaritmes', 'ln_plus_product', 5, 2, 'Bepaal $u''(x) = 2x$ en $v''(x) = \dfrac{2}{2x} = \dfrac{1}{x}$ (kettingregel).'),
  ('h9_logaritmes', 'ln_plus_product', 5, 3, 'Pas de productregel toe: $f''(x) = 2x\ln(2x) + x^2 \cdot \dfrac{1}{x} = 2x\ln(2x) + x$.'),
  ('h9_logaritmes', 'ln_plus_product', 6, 1, 'Herken de productregel: $u(x) = x$ en $v(x) = \ln(2x+1)$.'),
  ('h9_logaritmes', 'ln_plus_product', 6, 2, 'Bepaal $u''(x) = 1$ en $v''(x) = \dfrac{2}{2x+1}$ (kettingregel).'),
  ('h9_logaritmes', 'ln_plus_product', 6, 3, 'Pas de productregel toe: $k''(x) = \ln(2x+1) + x \cdot \dfrac{2}{2x+1} = \ln(2x+1) + \dfrac{2x}{2x+1}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 1, 1, 'Benoem: $t(x) = \ln(x)$ en $n(x) = x$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 1, 2, 'Bepaal $t''(x) = \dfrac{1}{x}$ en $n''(x) = 1$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 1, 3, '$f''(x) = \dfrac{\frac{1}{x} \cdot x - \ln(x) \cdot 1}{x^2} = \dfrac{1 - \ln(x)}{x^2}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 2, 1, 'Benoem: $t(x) = \ln(x)+1$ en $n(x) = x$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 2, 2, 'Bepaal $t''(x) = \dfrac{1}{x}$ en $n''(x) = 1$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 2, 3, '$f''(x) = \dfrac{\frac{1}{x} \cdot x - (\ln(x)+1) \cdot 1}{x^2} = \dfrac{1 - \ln(x) - 1}{x^2} = -\dfrac{\ln(x)}{x^2}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 3, 1, 'Benoem: $t(x) = x$ en $n(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 3, 2, 'Bepaal $t''(x) = 1$ en $n''(x) = \dfrac{1}{x}$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 3, 3, '$g''(x) = \dfrac{\ln(x) - x \cdot \frac{1}{x}}{\ln^2(x)} = \dfrac{\ln(x) - 1}{\ln^2(x)}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 4, 1, 'Benoem: $t(x) = \ln(x)$ en $n(x) = x^2$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 4, 2, 'Bepaal $t''(x) = \dfrac{1}{x}$ en $n''(x) = 2x$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 4, 3, '$h''(x) = \dfrac{\frac{1}{x} \cdot x^2 - \ln(x) \cdot 2x}{x^4} = \dfrac{x - 2x\ln(x)}{x^4} = \dfrac{1 - 2\ln(x)}{x^3}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 5, 1, 'Benoem: $t(x) = x^2$ en $n(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 5, 2, 'Bepaal $t''(x) = 2x$ en $n''(x) = \dfrac{1}{x}$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 5, 3, '$f''(x) = \dfrac{2x \cdot \ln(x) - x^2 \cdot \frac{1}{x}}{\ln^2(x)} = \dfrac{2x\ln(x) - x}{\ln^2(x)}$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 6, 1, 'Benoem: $t(x) = x+1$ en $n(x) = \ln(x)$.'),
  ('h9_logaritmes', 'ln_plus_quotient', 6, 2, 'Bepaal $t''(x) = 1$ en $n''(x) = \dfrac{1}{x}$. Pas de quotiëntregel toe.'),
  ('h9_logaritmes', 'ln_plus_quotient', 6, 3, '$k''(x) = \dfrac{\ln(x) - (x+1) \cdot \frac{1}{x}}{\ln^2(x)} = \dfrac{\ln(x) - \frac{x+1}{x}}{\ln^2(x)}$.')
) AS s(topic_slug, cluster_slug, q_order, step_order, description)
JOIN public.topics_new t          ON t.slug    = s.topic_slug
JOIN public.topic_clusters_new tc ON tc.slug   = s.cluster_slug AND tc.topic_id = t.id
JOIN public.questions_new q       ON q.cluster_id = tc.id AND q.order_index = s.q_order;

-- Validatie
SELECT 'question_steps_new' AS tbl, COUNT(*)::text AS n FROM public.question_steps_new;
-- Verwacht: 184 (H2) + 198 (H6) + 119 (H7) + 162 (H9) = 663

COMMIT;